version: 0.2

phases:
  install:
    commands:
      - rm /root/.m2/settings.xml
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - aws s3 cp s3://endeavour-codebuild/settings/settings.xml /root/.m2/settings.xml
  build:
    commands:
      - chmod +x aws_scripts/build.sh
      - echo IM Build started on `date`
      - aws_scripts/build.sh mvn -B deploy
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
